### ISSUE TITLE
Properties are missing

### ISSUE THREAD

**Issue by lekve11** [kvandake/SCLAlertView-Xamarin#1]
//Override top circle tint color with background color
alert.tintTopCircle = NO;

//Set custom corner radius for SCLAlertView
alert.cornerRadius = 13.0f;

//Overwrite SCLAlertView background color
alert.backgroundViewColor = [UIColor cyanColor];

**Comment by kvandake** [comment]
Thanks, I try make cross platform InteractiveAlerts. Please see my branch feature/interactive_alerts. And I [Pull Request(](https://github.com/aritchie/userdialogs/pull/378)Work in progress) to Acr.UserDialogs. Your question will be resolved in the following releases.
