### ISSUE TITLE
How can I dissmis AlertView ?

### ISSUE THREAD

**Issue by tornikegomareli** [kvandake/SCLAlertView-Xamarin#3]
I'm using this library for my UiAlertController.

 I want to dismiss view when the user clicks outside of it? 

How can I do this? Can someone help? Thanks

**Comment by kvandake** [comment]
You can use the property [IsCancelable](https://github.com/kvandake/InteractiveAlert-Xamarin/blob/master/InteractiveAlert/InteractiveAlert.Core/InteractiveAlertConfig.cs#L46) in [InteractiveAlertConfig](https://github.com/kvandake/InteractiveAlert-Xamarin/blob/master/InteractiveAlert/InteractiveAlert.Core/InteractiveAlertConfig.cs). If the value of IsCancelable is set to True, then the alert closes when the user clicks outside of the alert.

**Comment by kvandake** [comment]
You can see my [commit](https://github.com/kvandake/InteractiveAlert-Xamarin/commit/6ba667d2587edeed677b040a495c31de000fc5e2). I added global events for InteractiveAlertView(iOS):
* Presented;
* Closed. 

You can use [InteractiveAlertView.Presented](https://github.com/kvandake/InteractiveAlert-Xamarin/blob/master/InteractiveAlert/InteractiveAlert.iOS/InteractiveAlertView.cs#L1261), InteractiveAlertView.Closed for the presentation settings.
The new feature will be available in version **0.1.7**.
Thanks for feedback!

**Comment by tornikegomareli** [comment]
Thank you very much. Sory for the late response. I solved this problem with your help.
